### ISSUE TITLE
There was a problem loading the calibration file. Check the URL!

### ISSUE THREAD

**Issue by chenhui1025** [PaolaArdon/Salt-Pepper#1]
Hello!

When I run $rosrun ORB_SLAM2 RGBD /home/turtlebot/orb_slam2/Vocabulary/ORBvoc.bin /home/turtlebot/orb_slam2/Examples/RGB-D/pepperCameraSettings.yaml false.
There is no image in ORB_SLAM2:Map Viewer or ORB_SLAM2:Current frame.However there are some error in the terminal that I run $roslaunch pepper_bringup pepper_full_py.launch nao_ip:=192.168.0.109 roscore_ip:=192.168.0.205 .
[INFO] [WallTime: 1495527611.363963] reconfigure changed
[INFO] [WallTime: 1495527611.364529] subscribed to camera proxy, since this is the first camera
[INFO] [WallTime: 1495527611.375039] updating camera source information
[INFO] [WallTime: 1495527611.375651] no valid camera calibration file found
[INFO] [WallTime: 1495527611.376092] camera calibration URL: file:///home/turtlebot/.ros/camera_info/nao_camera.yaml
[ERROR] [WallTime: 1495527611.376594] There was a problem loading the calibration file. Check the URL!
PS:I can view the image from rviz
Hope for your answer. Thanks a lot.

**Comment by chenhui1025** [comment]
I copy the nao_camera_top-640*480.yaml to URL: file:///home/turtlebot/.ros/camera_info/nao_camera.yaml
there is no wrong in pepper_bring terminal:
[INFO] [WallTime: 1495531170.460287] reconfigure changed
[INFO] [WallTime: 1495531170.460958] subscribed to camera proxy, since this is the first camera
[INFO] [WallTime: 1495531170.537999] updating camera source information
[INFO] [WallTime: 1495531170.538710] no valid camera calibration file found
[INFO] [WallTime: 1495531170.539264] camera calibration URL: file:///home/turtlebot/.ros/camera_info/nao_camera.yaml
[INFO] [WallTime: 1495531170.560160] Successfully loaded camera info
[INFO] [WallTime: 1495531171.224173] updating camera source information
However there still no image in ORB_SLAM2:Map Viewer or ORB_SLAM2:Current frame.

**Comment by pianoza** [comment]
Hi @chenhui1025,
We don't have an access to the pepper robot now, and the following 2-3 weeks we'll be loaded with other projects. I'll check the issue when I get some time.
For now, you could try to run the ORB_SLAM2 separately (with your webcam), without linking it to any robot, and start working around from there.
Cheers!

**Comment by chenhui1025** [comment]
Hi @pianoza  Thanks for reply. Do you still remember you get the camera calibration yaml yourself or use the nao_camera.yaml in package naoqi_sensor_py.
Cheers!

**Comment by pengsongyou** [comment]
@chenhui1025 Hi. We calibrated the RGB camera by ourselves with the help of OpenCV. However, if I was not mistaken, ORB-SLAM was still working even before the calibration, right? @pianoza

**Comment by pianoza** [comment]
@pengsongyou yes, it should work. @chenhui1025, the calibration only affects the 3D reconstruction, so it should work with nao_camera.yaml config with no problem (of course the accuracy will suffer if the camera is not calibrated).

**Comment by chenhui1025** [comment]
@pengsongyou @pianoza Thanks !I will try the ORB_SLAM2 with my RGB-D camera .  I was confused with the code in https://github.com/PaolaArdon/Salt-Pepper/tree/master/orb_slam2/Examples/ROS/ORB_SLAM2/src/ros_rgbd.cc
line 76: message_filters::Subscriber<sensor_msgs::Image> rgb_sub(nh, "/camera/image_raw",is the topic "/camera/image_raw" right?Why not be "/pepper_robot/camera/front/camera/image_raw" if we link it to pepper.

**Comment by chenhui1025** [comment]
@pianoza Hi, sorry for disturbing you again. I have tried my RGB-D camera with the original ORB_SLAM2 by raulmur and the modified ORB_SLAM2 by your team. However it's OK with the original one and it's still no image with your's . I run $rosrun rqt_graph rqt_graph and I get the same result. So I wonder if there something wrong with the command: $ rosrun ORB_SLAM2 RGBD /home/xx/orb_slam2/Vocabulary/ORBvoc.bin /home/xx/orb_slam2/Examples/RGB-/pepperCameraSettings.yaml false.Thanks a lot .

**Comment by pianoza** [comment]
@chenhui1025, probably you're trying to subscribe to non-existing rostopics. Make sure that the names of the topics are correct for the following lines (in ros_rgbd.cc). Check all the .lunch files as well, there are some mappings of the topic names (don't remember which .lunch file exactly).

> message_filters::Subscriber<sensor_msgs::Image> rgb_sub(nh, "/camera/image_raw", 1);
>     message_filters::Subscriber<sensor_msgs::Image> depth_sub(nh, "/pepper_robot/camera/depth/camera/image_raw", 1);
> message_filters::Subscriber<sensor_msgs::Temperature> recog_sub(nh, "/recog", 1);
> 

Also, note that the depth and rgb images must be synchronized (i.e. must have the same timestamp in headers of the messages).

**Comment by chenhui1025** [comment]
@pianoza ,I have checked rostopics . There is no error with topic and I succeed to run ORB_SLAM2(Raul Mul) with pepper. What confused me most is that I cannot run the ORB_SLAM2 from your github.

**Comment by chenhui1025** [comment]
@pianoza Can you show me the command for building map. My command is:$rosrun ORB_SLAM2 RGBD /home/xx/orb_slam2/Vocabulary/ORBvoc.bin /home/xx/orb_slam2/Examples/RGB-/pepperCameraSettings.yaml false. Is it anything wrong with that?

**Comment by chenhui1025** [comment]
Hi ,@pengsongyou @pianoza, how do you deal with the problem that too much delay between pepper and pc. In my pc there are about several seconds per frame. Thanks a lot.
