### ISSUE TITLE
problem of finding naoqi

### ISSUE THREAD

**Issue by lengagne** [PaolaArdon/Salt-Pepper#2]
Hi,

We are followng your tuto and when we run the command
"rosrun joy_pepper joypepper.py"
We got the following error message : 
Traceback (most recent call last):
  File "/home/user/Bureau/catkin_ws/src/Salt-Pepper/joy_pepper/scripts/joypepper.py", line 11, in <module>
    from naoqi import ALProxy
ImportError: No module named naoqi

We are using ubuntu 16 and ros-kinetic

Can you help us

**Comment by pengsongyou** [comment]
Hi lengagne,

You probably need to install NAOqi first. Please check the link http://doc.aldebaran.com/2-1/dev/python/install_guide.html for more installation information.
